export const servicesInfo = [
	{
		slug: "create-an-account",
		title: "Створити обліковий запис",
		desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lobortis feugiat vivamus at augue eget arcu dictum varius duis. Dictum at tempor commodo ullamcorper a lacus. Id consectetur purus ut faucibus pulvinar elementum integer. Scelerisque eu ultrices vitae auctor eu augue ut lectus. Lectus quam id leo in vitae turpis massa. Cursus risus at ultrices mi tempus imperdiet. Cursus metus aliquam eleifend mi in nulla. At augue eget arcu dictum varius duis at consectetur. Fermentum posuere urna nec tincidunt praesent. Mattis nunc sed blandit libero volutpat sed cras ornare. Porta non pulvinar neque laoreet suspendisse interdum. Augue ut lectus arcu bibendum. Euismod nisi porta lorem mollis. Nibh praesent tristique magna sit amet. Scelerisque viverra mauris in aliquam sem fringilla ut morbi tincidunt. Malesuada fames ac turpis egestas. Dictumst quisque sagittis purus sit amet volutpat consequat. Vestibulum lectus mauris ultrices eros in cursus turpis massa tincidunt. Consequat mauris nunc congue nisi vitae suscipit tellus mauris a. Sit amet justo donec enim diam vulputate ut pharetra sit. Non tellus orci ac auctor augue mauris augue. Phasellus egestas tellus rutrum tellus pellentesque eu.",
	},
	{
		slug: "complete-your-profile",
		title: "Заповніть свій профіль",
		desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lobortis feugiat vivamus at augue eget arcu dictum varius duis. Dictum at tempor commodo ullamcorper a lacus. Id consectetur purus ut faucibus pulvinar elementum integer. Scelerisque eu ultrices vitae auctor eu augue ut lectus. Lectus quam id leo in vitae turpis massa. Cursus risus at ultrices mi tempus imperdiet. Cursus metus aliquam eleifend mi in nulla. At augue eget arcu dictum varius duis at consectetur. Fermentum posuere urna nec tincidunt praesent. Mattis nunc sed blandit libero volutpat sed cras ornare. Porta non pulvinar neque laoreet suspendisse interdum. Augue ut lectus arcu bibendum. Euismod nisi porta lorem mollis. Nibh praesent tristique magna sit amet. Scelerisque viverra mauris in aliquam sem fringilla ut morbi tincidunt. Malesuada fames ac turpis egestas. Dictumst quisque sagittis purus sit amet volutpat consequat. Vestibulum lectus mauris ultrices eros in cursus turpis massa tincidunt. Consequat mauris nunc congue nisi vitae suscipit tellus mauris a. Sit amet justo donec enim diam vulputate ut pharetra sit. Non tellus orci ac auctor augue mauris augue. Phasellus egestas tellus rutrum tellus pellentesque eu.",
	},
	{
		slug: "search",
		title: "Шукайте що Вам потрібно",
		desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lobortis feugiat vivamus at augue eget arcu dictum varius duis. Dictum at tempor commodo ullamcorper a lacus. Id consectetur purus ut faucibus pulvinar elementum integer. Scelerisque eu ultrices vitae auctor eu augue ut lectus. Lectus quam id leo in vitae turpis massa. Cursus risus at ultrices mi tempus imperdiet. Cursus metus aliquam eleifend mi in nulla. At augue eget arcu dictum varius duis at consectetur. Fermentum posuere urna nec tincidunt praesent. Mattis nunc sed blandit libero volutpat sed cras ornare. Porta non pulvinar neque laoreet suspendisse interdum. Augue ut lectus arcu bibendum. Euismod nisi porta lorem mollis. Nibh praesent tristique magna sit amet. Scelerisque viverra mauris in aliquam sem fringilla ut morbi tincidunt. Malesuada fames ac turpis egestas. Dictumst quisque sagittis purus sit amet volutpat consequat. Vestibulum lectus mauris ultrices eros in cursus turpis massa tincidunt. Consequat mauris nunc congue nisi vitae suscipit tellus mauris a. Sit amet justo donec enim diam vulputate ut pharetra sit. Non tellus orci ac auctor augue mauris augue. Phasellus egestas tellus rutrum tellus pellentesque eu.",
	},
];
export const jobListInfo = [
	{
		id: 1,
		title: "Big Data Software Engineer Specialist",
		desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
		type: "full time",
		city: "Praha",
		atDate: new Date(),
		salery: 125,
		img: "/home_main.jpg",
	},
	{
		id: 2,
		title: "Big Data Software Engineer Specialist",
		desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
		type: "full time",
		city: "Praha",
		atDate: new Date(),
		salery: 125,
		img: "/home_main.jpg",
	},
	{
		id: 3,
		title: "Big Data Software Engineer Specialist",
		desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
		type: "full time",
		city: "Praha",
		atDate: new Date(),
		salery: 125,
		img: "/home_main.jpg",
	},
];

export const jobTypes = [
	{
		value: "full",
		label: "Повна занятість",
	},
	{
		value: "part-time",
		label: "Часткова занятість",
	},
	{
		value: "one-time",
		label: "Одноразова робота",
	},
];

export const candidatesListInfo = [
	{
		id: 1,
		desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been.",
		name: "David",
		surname: "Warner",
		phonenumber: "+380991241055",
		email: "davidwarner@gmail.com",
		city: "Praha",
		mainJob: "Developer",
		languageSkill: "начальный",
		salery: 125,
		age: 41,
		skills: [
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Fullstack developer", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
		],
		img: "/assets/icons/avatar.svg",
	},
	{
		id: 2,
		desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been.",
		name: "David",
		surname: "Warner",
		phonenumber: "+380991241055",
		email: "davidwarner@gmail.com",
		city: "Praha",
		mainJob: "Developer",
		languageSkill: "начальный",
		salery: 125,
		age: 31,
		skills: [
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
		],
		img: "/assets/icons/avatar.svg",
	},
	{
		id: 3,
		desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been.",
		name: "David",
		surname: "Warner",
		phonenumber: "+380991241055",
		email: "davidwarner@gmail.com",
		city: "Praha",
		mainJob: "Developer",
		languageSkill: "начальный",
		salery: 125,
		age: 31,
		skills: [
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
		],
		img: "/assets/icons/avatar.svg",
	},
	{
		id: 4,
		desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been.",
		name: "David",
		surname: "Warner",
		phonenumber: "+380991241055",
		email: "davidwarner@gmail.com",
		city: "Praha",
		mainJob: "Developer",
		languageSkill: "начальный",
		salery: 125,
		age: 31,
		skills: [
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
		],
		img: "/assets/icons/avatar.svg",
	},
	{
		id: 5,
		desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been.",
		name: "David",
		surname: "Warner",
		phonenumber: "+380991241055",
		email: "davidwarner@gmail.com",
		city: "Praha",
		mainJob: "Developer",
		languageSkill: "начальный",
		salery: 125,
		age: 31,
		skills: [
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
		],
		img: "/assets/icons/avatar.svg",
	},
	{
		id: 6,
		desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been.",
		name: "David",
		surname: "Warner",
		phonenumber: "+380991241055",
		email: "davidwarner@gmail.com",
		city: "Praha",
		mainJob: "Developer",
		languageSkill: "начальный",
		salery: 125,
		age: 31,
		skills: [
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
		],
		img: "/assets/icons/avatar.svg",
	},
	{
		id: 7,
		desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been.",
		name: "David",
		surname: "Warner",
		phonenumber: "+380991241055",
		email: "davidwarner@gmail.com",
		city: "Praha",
		mainJob: "Developer",
		languageSkill: "начальный",
		salery: 125,
		age: 31,
		skills: [
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
		],
		img: "/assets/icons/avatar.svg",
	},
	{
		id: 8,
		desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been.",
		name: "David",
		surname: "Warner",
		phonenumber: "+380991241055",
		email: "davidwarner@gmail.com",
		city: "Praha",
		mainJob: "Developer",
		languageSkill: "начальный",
		salery: 125,
		age: 31,
		skills: [
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
		],
		img: "/assets/icons/avatar.svg",
	},
	{
		id: 9,
		desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been.",
		name: "David",
		surname: "Warner",
		phonenumber: "+380991241055",
		email: "davidwarner@gmail.com",
		city: "Praha",
		mainJob: "Developer",
		languageSkill: "начальный",
		salery: 125,
		age: 31,
		skills: [
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
		],
		img: "/assets/icons/avatar.svg",
	},
	{
		id: 10,
		desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been.",
		name: "David",
		surname: "Warner",
		phonenumber: "+380991241055",
		email: "davidwarner@gmail.com",
		city: "Praha",
		mainJob: "Developer",
		languageSkill: "начальный",
		salery: 125,
		age: 31,
		skills: [
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
		],
		img: "/assets/icons/avatar.svg",
	},
	{
		id: 11,
		desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been.",
		name: "David",
		surname: "Warner",
		phonenumber: "+380991241055",
		email: "davidwarner@gmail.com",
		city: "Praha",
		mainJob: "Developer",
		languageSkill: "начальный",
		salery: 125,
		age: 31,
		skills: [
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
		],
		img: "/assets/icons/avatar.svg",
	},
	{
		id: 12,
		desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been.",
		name: "David",
		surname: "Warner",
		phonenumber: "+380991241055",
		email: "davidwarner@gmail.com",
		city: "Praha",
		mainJob: "Developer",
		languageSkill: "начальный",
		salery: 125,
		age: 31,
		skills: [
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
		],
		img: "/assets/icons/avatar.svg",
	},
	{
		id: 13,
		desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been.",
		name: "David",
		surname: "Warner",
		phonenumber: "+380991241055",
		email: "davidwarner@gmail.com",
		city: "Praha",
		mainJob: "Developer",
		languageSkill: "начальный",
		salery: 125,
		age: 31,
		skills: [
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
		],
		img: "/assets/icons/avatar.svg",
	},
	{
		id: 14,
		desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been.",
		name: "David",
		surname: "Warner",
		phonenumber: "+380991241055",
		email: "davidwarner@gmail.com",
		city: "Praha",
		mainJob: "Developer",
		languageSkill: "начальный",
		salery: 125,
		age: 31,
		skills: [
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
		],
		img: "/assets/icons/avatar.svg",
	},
	{
		id: 15,
		desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been.",
		name: "David",
		surname: "Warner",
		phonenumber: "+380991241055",
		email: "davidwarner@gmail.com",
		city: "Praha",
		mainJob: "Developer",
		languageSkill: "начальный",
		salery: 125,
		age: 31,
		skills: [
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
		],
		img: "/assets/icons/avatar.svg",
	},
	{
		id: 16,
		desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been.",
		name: "David",
		surname: "Warner",
		phonenumber: "+380991241055",
		email: "davidwarner@gmail.com",
		city: "Praha",
		mainJob: "Developer",
		languageSkill: "начальный",
		salery: 125,
		age: 31,
		skills: [
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
		],
		img: "/assets/icons/avatar.svg",
	},
	{
		id: 17,
		desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been.",
		name: "David",
		surname: "Warner",
		phonenumber: "+380991241055",
		email: "davidwarner@gmail.com",
		city: "Praha",
		mainJob: "Developer",
		languageSkill: "начальный",
		salery: 125,
		age: 31,
		skills: [
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
		],
		img: "/assets/icons/avatar.svg",
	},
	{
		id: 18,
		desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been.",
		name: "David",
		surname: "Warner",
		phonenumber: "+380991241055",
		email: "davidwarner@gmail.com",
		city: "Praha",
		mainJob: "Developer",
		languageSkill: "начальный",
		salery: 125,
		age: 31,
		skills: [
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
		],
		img: "/assets/icons/avatar.svg",
	},
	{
		id: 19,
		desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been.",
		name: "David",
		surname: "Warner",
		phonenumber: "+380991241055",
		email: "davidwarner@gmail.com",
		city: "Praha",
		mainJob: "Developer",
		languageSkill: "начальный",
		salery: 125,
		age: 31,
		skills: [
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
			{ desc: "Водій", from: "06.2012", to: "02.2022" },
		],
		img: "/assets/icons/avatar.svg",
	},
];
