export const servicesInfo = [
	{
		slug: "create-an-account",
		title: "Створити обліковий запис",
		desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lobortis feugiat vivamus at augue eget arcu dictum varius duis. Dictum at tempor commodo ullamcorper a lacus. Id consectetur purus ut faucibus pulvinar elementum integer. Scelerisque eu ultrices vitae auctor eu augue ut lectus. Lectus quam id leo in vitae turpis massa. Cursus risus at ultrices mi tempus imperdiet. Cursus metus aliquam eleifend mi in nulla. At augue eget arcu dictum varius duis at consectetur. Fermentum posuere urna nec tincidunt praesent. Mattis nunc sed blandit libero volutpat sed cras ornare. Porta non pulvinar neque laoreet suspendisse interdum. Augue ut lectus arcu bibendum. Euismod nisi porta lorem mollis. Nibh praesent tristique magna sit amet. Scelerisque viverra mauris in aliquam sem fringilla ut morbi tincidunt. Malesuada fames ac turpis egestas. Dictumst quisque sagittis purus sit amet volutpat consequat. Vestibulum lectus mauris ultrices eros in cursus turpis massa tincidunt. Consequat mauris nunc congue nisi vitae suscipit tellus mauris a. Sit amet justo donec enim diam vulputate ut pharetra sit. Non tellus orci ac auctor augue mauris augue. Phasellus egestas tellus rutrum tellus pellentesque eu.",
	},
	{
		slug: "complete-your-profile",
		title: "Заповніть свій профіль",
		desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lobortis feugiat vivamus at augue eget arcu dictum varius duis. Dictum at tempor commodo ullamcorper a lacus. Id consectetur purus ut faucibus pulvinar elementum integer. Scelerisque eu ultrices vitae auctor eu augue ut lectus. Lectus quam id leo in vitae turpis massa. Cursus risus at ultrices mi tempus imperdiet. Cursus metus aliquam eleifend mi in nulla. At augue eget arcu dictum varius duis at consectetur. Fermentum posuere urna nec tincidunt praesent. Mattis nunc sed blandit libero volutpat sed cras ornare. Porta non pulvinar neque laoreet suspendisse interdum. Augue ut lectus arcu bibendum. Euismod nisi porta lorem mollis. Nibh praesent tristique magna sit amet. Scelerisque viverra mauris in aliquam sem fringilla ut morbi tincidunt. Malesuada fames ac turpis egestas. Dictumst quisque sagittis purus sit amet volutpat consequat. Vestibulum lectus mauris ultrices eros in cursus turpis massa tincidunt. Consequat mauris nunc congue nisi vitae suscipit tellus mauris a. Sit amet justo donec enim diam vulputate ut pharetra sit. Non tellus orci ac auctor augue mauris augue. Phasellus egestas tellus rutrum tellus pellentesque eu.",
	},
	{
		slug: "search",
		title: "Шукайте що Вам потрібно",
		desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lobortis feugiat vivamus at augue eget arcu dictum varius duis. Dictum at tempor commodo ullamcorper a lacus. Id consectetur purus ut faucibus pulvinar elementum integer. Scelerisque eu ultrices vitae auctor eu augue ut lectus. Lectus quam id leo in vitae turpis massa. Cursus risus at ultrices mi tempus imperdiet. Cursus metus aliquam eleifend mi in nulla. At augue eget arcu dictum varius duis at consectetur. Fermentum posuere urna nec tincidunt praesent. Mattis nunc sed blandit libero volutpat sed cras ornare. Porta non pulvinar neque laoreet suspendisse interdum. Augue ut lectus arcu bibendum. Euismod nisi porta lorem mollis. Nibh praesent tristique magna sit amet. Scelerisque viverra mauris in aliquam sem fringilla ut morbi tincidunt. Malesuada fames ac turpis egestas. Dictumst quisque sagittis purus sit amet volutpat consequat. Vestibulum lectus mauris ultrices eros in cursus turpis massa tincidunt. Consequat mauris nunc congue nisi vitae suscipit tellus mauris a. Sit amet justo donec enim diam vulputate ut pharetra sit. Non tellus orci ac auctor augue mauris augue. Phasellus egestas tellus rutrum tellus pellentesque eu.",
	},
];

export const employerListInfo = [
	{
		id: 33,
		companyname: "Tyno corporation",
		phonenumber: "+380991241055",
		email: "berhaneselassie1945@gmail.com",
		website: "https://web.dotthemes.com/",
		image: "/qa-photo.jpg",
	},
];

export const jobListInfo = [
	{
		id: 1,
		title: "Big Data Software Engineer Specialist",
		desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
		type: "Повна",
		category: "Ostatní",
		languageSkill: "Комунікативний",
		obec: "Praha",
		city: "Praha",
		address: "Otakarova 10",
		atDate: "25-06-1992",
		salary: "125",
		img: "/home_main.jpg",
		duties: [
			"Conduct research to make evidence-based improvements to current methods of on-campus and online leadership courses",
			"Teach and facilitate in the leadership development programs",
			"Assist in planning and designing curriculum for the leadership programs",
			"Prepare guidelines and schedule for leadership sessions, activities, and small group discussions",
			"Supervise and monitor the work and performance of participants during the training programs",
			"Facilitate community service projects",
			"Ensure documentation of all training related activities",
			"Serve in the Admissions of committee of different BYLC programs",
		],
		bonuses: [
			"5Conduct research to make evidence-based improvements to current methods of on-campus and online leadership courses",
			"5Teach and facilitate in the leadership development programs",
			"5Assist in planning and designing curriculum for the leadership programs",
			"5Prepare guidelines and schedule for leadership sessions, activities, and small group discussions",
			"5Supervise and monitor the work and performance of participants during the training programs",
			"5Facilitate community service projects",
			"5Ensure documentation of all training related activities",
			"5Serve in the Admissions of committee of different BYLC programs",
		],
	},
	{
		id: 2,
		title: "Big Data Software Engineer Specialist",
		desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
		type: "Повна",
		category: "Ostatní",
		languageSkill: "Комунікативний",
		obec: "Praha",
		city: "Praha",
		address: "Otakarova 10",
		atDate: "25-06-1992",
		salary: "125",
		img: "/home_main.jpg",
		duties: [
			"Conduct research to make evidence-based improvements to current methods of on-campus and online leadership courses",
			"Teach and facilitate in the leadership development programs",
			"Assist in planning and designing curriculum for the leadership programs",
			"Prepare guidelines and schedule for leadership sessions, activities, and small group discussions",
			"Supervise and monitor the work and performance of participants during the training programs",
			"Facilitate community service projects",
			"Ensure documentation of all training related activities",
			"Serve in the Admissions of committee of different BYLC programs",
		],
		bonuses: [
			"Conduct research to make evidence-based improvements to current methods of on-campus and online leadership courses",
			"Teach and facilitate in the leadership development programs",
			"Assist in planning and designing curriculum for the leadership programs",
			"Prepare guidelines and schedule for leadership sessions, activities, and small group discussions",
			"Supervise and monitor the work and performance of participants during the training programs",
			"Facilitate community service projects",
			"Ensure documentation of all training related activities",
			"Serve in the Admissions of committee of different BYLC programs",
		],
	},
	{
		id: 3,
		title: "Big Data Software Engineer Specialist",
		desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
		type: "Повна",
		category: "Ostatní",
		languageSkill: "Комунікативний",
		obec: "Praha",
		city: "Praha",
		address: "Otakarova 10",
		atDate: "25-06-1992",
		salary: "125",
		img: "/home_main.jpg",
		duties: [
			"Conduct research to make evidence-based improvements to current methods of on-campus and online leadership courses",
			"Teach and facilitate in the leadership development programs",
			"Assist in planning and designing curriculum for the leadership programs",
			"Prepare guidelines and schedule for leadership sessions, activities, and small group discussions",
			"Supervise and monitor the work and performance of participants during the training programs",
			"Facilitate community service projects",
			"Ensure documentation of all training related activities",
			"Serve in the Admissions of committee of different BYLC programs",
		],
		bonuses: [
			"Conduct research to make evidence-based improvements to current methods of on-campus and online leadership courses",
			"Teach and facilitate in the leadership development programs",
			"Assist in planning and designing curriculum for the leadership programs",
			"Prepare guidelines and schedule for leadership sessions, activities, and small group discussions",
			"Supervise and monitor the work and performance of participants during the training programs",
			"Facilitate community service projects",
			"Ensure documentation of all training related activities",
			"Serve in the Admissions of committee of different BYLC programs",
		],
	},
];

export const jobTypes = [
	{
		value: "full",
		label: "Повна занятість",
	},
	{
		value: "part-time",
		label: "Часткова занятість",
	},
	{
		value: "one-time",
		label: "Одноразова робота",
	},
];

export const candidatesListInfo = [
	{
		id: 1,
		description:
			"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been.",
		name: "David",
		surname: "Warner",
		phonenumber: "+380991241055",
		email: "davidwarner@gmail.com",
		city: "Praha",
		address: "Otakarova 10",
		mainJob: "Ostatní",
		languageSkill: "Початковий",
		salary: "125",
		age: "41",
		skills: [
			{ vacancy: "Ostatní", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Ostatní", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Ostatní", startDate: "06.2012", endDate: "02.2022" },
			{
				vacancy: "Fullstack developer",
				startDate: "06.2012",
				endDate: "02.2022",
			},
			{ vacancy: "Ostatní", startDate: "06.2012", endDate: "02.2022" },
		],
		img: "/assets/icons/avatar.svg",
	},
	{
		id: 2,
		description:
			"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been.",
		name: "David",
		surname: "Warner",
		phonenumber: "+380991241055",
		email: "davidwarner@gmail.com",
		city: "Praha",
		mainJob: "Developer",
		languageSkill: "Початковий",
		salary: "125",
		age: "31",
		skills: [
			{ vacancy: "Ostatní", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Ostatní", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Ostatní", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Ostatní", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Ostatní", startDate: "06.2012", endDate: "02.2022" },
		],
		img: "/assets/icons/avatar.svg",
	},
	{
		id: 3,
		description:
			"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been.",
		name: "David",
		surname: "Warner",
		phonenumber: "+380991241055",
		email: "davidwarner@gmail.com",
		city: "Praha",
		mainJob: "Developer",
		languageSkill: "Початковий",
		salary: "125",
		age: "31",
		skills: [
			{ vacancy: "Ostatní", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Ostatní", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Ostatní", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Ostatní", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Ostatní", startDate: "06.2012", endDate: "02.2022" },
		],
		img: "/assets/icons/avatar.svg",
	},
	{
		id: 4,
		description:
			"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been.",
		name: "David",
		surname: "Warner",
		phonenumber: "+380991241055",
		email: "davidwarner@gmail.com",
		city: "Praha",
		mainJob: "Developer",
		languageSkill: "Початковий",
		salary: "125",
		age: "31",
		skills: [
			{ vacancy: "Ostatní", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Ostatní", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Ostatní", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
		],
		img: "/assets/icons/avatar.svg",
	},
	{
		id: 5,
		description:
			"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been.",
		name: "David",
		surname: "Warner",
		phonenumber: "+380991241055",
		email: "davidwarner@gmail.com",
		city: "Praha",
		mainJob: "Developer",
		languageSkill: "Початковий",
		salary: "125",
		age: "31",
		skills: [
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
		],
		img: "/assets/icons/avatar.svg",
	},
	{
		id: 6,
		description:
			"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been.",
		name: "David",
		surname: "Warner",
		phonenumber: "+380991241055",
		email: "davidwarner@gmail.com",
		city: "Praha",
		mainJob: "Developer",
		languageSkill: "Початковий",
		salary: "125",
		age: "31",
		skills: [
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
		],
		img: "/assets/icons/avatar.svg",
	},
	{
		id: 7,
		description:
			"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been.",
		name: "David",
		surname: "Warner",
		phonenumber: "+380991241055",
		email: "davidwarner@gmail.com",
		city: "Praha",
		mainJob: "Developer",
		languageSkill: "Початковий",
		salary: "125",
		age: "31",
		skills: [
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
		],
		img: "/assets/icons/avatar.svg",
	},
	{
		id: 8,
		description:
			"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been.",
		name: "David",
		surname: "Warner",
		phonenumber: "+380991241055",
		email: "davidwarner@gmail.com",
		city: "Praha",
		mainJob: "Developer",
		languageSkill: "Початковий",
		salary: "125",
		age: "31",
		skills: [
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
		],
		img: "/assets/icons/avatar.svg",
	},
	{
		id: 9,
		description:
			"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been.",
		name: "David",
		surname: "Warner",
		phonenumber: "+380991241055",
		email: "davidwarner@gmail.com",
		city: "Praha",
		mainJob: "Developer",
		languageSkill: "Початковий",
		salary: "125",
		age: "31",
		skills: [
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
		],
		img: "/assets/icons/avatar.svg",
	},
	{
		id: 10,
		description:
			"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been.",
		name: "David",
		surname: "Warner",
		phonenumber: "+380991241055",
		email: "davidwarner@gmail.com",
		city: "Praha",
		mainJob: "Developer",
		languageSkill: "Початковий",
		salary: "125",
		age: "31",
		skills: [
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
		],
		img: "/assets/icons/avatar.svg",
	},
	{
		id: 11,
		description:
			"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been.",
		name: "David",
		surname: "Warner",
		phonenumber: "+380991241055",
		email: "davidwarner@gmail.com",
		city: "Praha",
		mainJob: "Developer",
		languageSkill: "Початковий",
		salary: "125",
		age: "31",
		skills: [
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
		],
		img: "/assets/icons/avatar.svg",
	},
	{
		id: 12,
		description:
			"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been.",
		name: "David",
		surname: "Warner",
		phonenumber: "+380991241055",
		email: "davidwarner@gmail.com",
		city: "Praha",
		mainJob: "Developer",
		languageSkill: "Початковий",
		salary: "125",
		age: "31",
		skills: [
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
		],
		img: "/assets/icons/avatar.svg",
	},
	{
		id: 13,
		description:
			"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been.",
		name: "David",
		surname: "Warner",
		phonenumber: "+380991241055",
		email: "davidwarner@gmail.com",
		city: "Praha",
		mainJob: "Developer",
		languageSkill: "Початковий",
		salary: "125",
		age: "31",
		skills: [
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
		],
		img: "/assets/icons/avatar.svg",
	},
	{
		id: 14,
		description:
			"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been.",
		name: "David",
		surname: "Warner",
		phonenumber: "+380991241055",
		email: "davidwarner@gmail.com",
		city: "Praha",
		mainJob: "Developer",
		languageSkill: "Початковий",
		salary: "125",
		age: "31",
		skills: [
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
		],
		img: "/assets/icons/avatar.svg",
	},
	{
		id: 15,
		description:
			"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been.",
		name: "David",
		surname: "Warner",
		phonenumber: "+380991241055",
		email: "davidwarner@gmail.com",
		city: "Praha",
		mainJob: "Developer",
		languageSkill: "Початковий",
		salary: "125",
		age: "31",
		skills: [
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
		],
		img: "/assets/icons/avatar.svg",
	},
	{
		id: 16,
		description:
			"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been.",
		name: "David",
		surname: "Warner",
		phonenumber: "+380991241055",
		email: "davidwarner@gmail.com",
		city: "Praha",
		mainJob: "Developer",
		languageSkill: "Початковий",
		salary: "125",
		age: "31",
		skills: [
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
		],
		img: "/assets/icons/avatar.svg",
	},
	{
		id: 17,
		description:
			"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been.",
		name: "David",
		surname: "Warner",
		phonenumber: "+380991241055",
		email: "davidwarner@gmail.com",
		city: "Praha",
		mainJob: "Developer",
		languageSkill: "Початковий",
		salary: "125",
		age: "31",
		skills: [
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
		],
		img: "/assets/icons/avatar.svg",
	},
	{
		id: 18,
		description:
			"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been.",
		name: "David",
		surname: "Warner",
		phonenumber: "+380991241055",
		email: "davidwarner@gmail.com",
		city: "Praha",
		mainJob: "Developer",
		languageSkill: "Початковий",
		salary: "125",
		age: "31",
		skills: [
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
		],
		img: "/assets/icons/avatar.svg",
	},
	{
		id: 19,
		description:
			"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been.",
		name: "David",
		surname: "Warner",
		phonenumber: "+380991241055",
		email: "davidwarner@gmail.com",
		city: "Praha",
		mainJob: "Developer",
		languageSkill: "Початковий",
		salary: "125",
		age: "31",
		skills: [
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
			{ vacancy: "Водій", startDate: "06.2012", endDate: "02.2022" },
		],
		img: "/assets/icons/avatar.svg",
	},
];
